"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _product_card from './product-card.bones.json'
import _product_page from './product-page.bones.json'
import _checkout_page from './checkout-page.bones.json'
import _order_history from './order-history.bones.json'
import _menu_categories from './menu-categories.bones.json'
import _menu_category_title from './menu-category-title.bones.json'
import _menu_header from './menu-header.bones.json'

registerBones({
  "product-card": _product_card,
  "product-page": _product_page,
  "checkout-page": _checkout_page,
  "order-history": _order_history,
  "menu-categories": _menu_categories,
  "menu-category-title": _menu_category_title,
  "menu-header": _menu_header,
})
